// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Bunsqlite from "bun:sqlite";

Buntest.describe("BunSqlite", () => {
  Buntest.test("basic commands work", () => {
    let db = new Bunsqlite.Database(":memory:");
    let resOne = db.query("SELECT 1").all();
    Buntest.expect(resOne).toEqual([{
        "1": 1
      }]);
    db.query("\nCREATE TABLE IF NOT EXISTS pokemon (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name TEXT NOT NULL\n);\n").run();
    let insertResult = db.query("INSERT INTO pokemon (name) VALUES (@name)").run({
      "@name": "Pikachu"
    });
    Buntest.expect(insertResult.lastInsertRowid).toBe(1);
    Buntest.expect(insertResult.changes).toBe(1);
    db.query("INSERT INTO pokemon (name) VALUES (@name)").run({
      "@name": "Raichu"
    });
    let allPokemons = db.query("SELECT * FROM pokemon ORDER BY id").all();
    Buntest.expect(allPokemons).toEqual([
      {
        id: 1,
        name: "Pikachu"
      },
      {
        id: 2,
        name: "Raichu"
      }
    ]);
    db.close();
  });
});

/*  Not a pure module */
