// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Buntest from "bun:test";

Buntest.describe("csrf", () => {
  Buntest.test("generate + verify with secret", () => {
    let secret = "test-secret";
    let token = $$Bun.CSRF.generate(secret);
    Buntest.expect($$Bun.CSRF.verify(token, {
      secret: secret
    })).toBeTrue();
  });
  Buntest.test("verify fails with wrong secret", () => {
    let token = $$Bun.CSRF.generate("correct-secret");
    Buntest.expect($$Bun.CSRF.verify(token, {
      secret: "wrong-secret"
    })).toBeFalse();
  });
  Buntest.test("generate with options (encoding + expires)", () => {
    let secret = "opts-secret";
    let token = $$Bun.CSRF.generate(secret, {
      expiresIn: 1000.0,
      encoding: "base64url"
    });
    Buntest.expect($$Bun.CSRF.verify(token, {
      secret: secret,
      encoding: "base64url"
    })).toBeTrue();
  });
});

/*  Not a pure module */
