// Generated by hand for CSRF runtime check
import {CSRF} from "bun";
import {describe, test, expect} from "bun:test";

describe("csrf", () => {
  test("generate + verify with secret", () => {
    const secret = "test-secret";
    const token = CSRF.generate(secret);
    expect(CSRF.verify(token, { secret })).toBe(true);
  });

  test("verify fails with wrong secret", () => {
    const token = CSRF.generate("correct-secret");
    expect(CSRF.verify(token, { secret: "wrong-secret" })).toBe(false);
  });

  test("generate with options (encoding + expires)", () => {
    const secret = "opts-secret";
    const token = CSRF.generate(secret, { encoding: "base64url", expiresIn: 1000 });
    expect(CSRF.verify(token, { secret, encoding: "base64url" })).toBe(true);
  });
});

