// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Buntest from "bun:test";

Buntest.describe("s3 presence", () => {
  Buntest.test("S3Client constructor and default instance available", () => {
    new $$Bun.S3Client({});
    Buntest.expect(true).toBeTrue();
  });
});

/*  Not a pure module */
