// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Buntest from "bun:test";

Buntest.describe("shell", () => {
  Buntest.test("basic commands work", async () => {
    let res = await $$Bun.$`echo HELLO`;
    Buntest.expect(res.stdout.toString()).toBe("HELLO\n");
  });
});

/*  Not a pure module */
