// Generated by ReScript, PLEASE EDIT WITH CARE


let rewriter = new HTMLRewriter();

rewriter.on("*", {
  element: element => {
    element.tagName = "span";
  }
});

let transformedResponse = rewriter.transform(new Response("<html><head></head><body><div>hellO!</div></body></html>"));

let html = await transformedResponse.text();

console.log(html);

export {
  rewriter,
  transformedResponse,
  html,
}
/* rewriter Not a pure module */
