// Generated by ReScript, PLEASE EDIT WITH CARE


var rewriter = new HTMLRewriter();

rewriter.on("*", {
      element: (function (element) {
          element.tagName = "span";
        })
    });

var transformedResponse = rewriter.transform(new Response("<html><head></head><body><div>hellO!</div></body></html>", undefined));

var html = await transformedResponse.text();

console.log(html);

export {
  rewriter ,
  transformedResponse ,
  html ,
}
/* rewriter Not a pure module */
