// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Stdlib_Null from "@rescript/runtime/lib/es6/Stdlib_Null.js";

let cookies = new $$Bun.CookieMap();

let cookies1 = new $$Bun.CookieMap("theme=dark; foo=bar");

let cookies2 = new $$Bun.CookieMap(Object.fromEntries([
  [
    "session",
    "abc123"
  ],
  [
    "theme",
    "dark"
  ]
]));

let cookies3 = new $$Bun.CookieMap([
  [
    "session",
    "abc123"
  ],
  [
    "theme",
    "dark"
  ]
]);

let theme1 = Stdlib_Null.getOr(cookies1.get("theme"), "light");

let theme2 = Stdlib_Null.getOr(cookies2.get("theme"), "light");

let theme3 = Stdlib_Null.getOr(cookies3.get("theme"), "light");

console.log(theme1, theme2, theme3);

export {
  cookies,
  cookies1,
  cookies2,
  cookies3,
  theme1,
  theme2,
  theme3,
}
/* cookies Not a pure module */
