// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Core__Null from "@rescript/core/src/Core__Null.js";

var cookies = new $$Bun.CookieMap();

var cookies1 = new $$Bun.CookieMap("theme=dark; foo=bar");

var cookies2 = new $$Bun.CookieMap(Object.fromEntries([
          [
            "session",
            "abc123"
          ],
          [
            "theme",
            "dark"
          ]
        ]));

var cookies3 = new $$Bun.CookieMap([
      [
        "session",
        "abc123"
      ],
      [
        "theme",
        "dark"
      ]
    ]);

var theme1 = Core__Null.getOr(cookies1.get("theme"), "light");

var theme2 = Core__Null.getOr(cookies2.get("theme"), "light");

var theme3 = Core__Null.getOr(cookies3.get("theme"), "light");

console.log(theme1, theme2, theme3);

export {
  cookies ,
  cookies1 ,
  cookies2 ,
  cookies3 ,
  theme1 ,
  theme2 ,
  theme3 ,
}
/* cookies Not a pure module */
