// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";

let response = await fetch("https://bun.sh");

let html = await response.text();

console.log(html);

let response$1 = await fetch("https://bun.sh/api", {
  body: Stdlib_Option.getOr(JSON.stringify({
    message: "Hello from Bun!"
  }), "-"),
  headers: [[
      "Content-Type",
      "application/json"
    ]],
  method: "POST"
});

let body = await response$1.json();

console.log(body);

export {
  html,
  response$1 as response,
  body,
}
/* response Not a pure module */
