// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as SQL$RescriptBun from "rescript-bun/src/SQL.js";

let mysql = new $$Bun.SQL("mysql://user:pass@localhost:3306/mydb");

let mysqlResults = await SQL$RescriptBun.query(mysql, [
  `
  SELECT * FROM users 
  WHERE active = `,
  `
`
], [true]);

let sqlite = new $$Bun.SQL("sqlite://myapp.db");

let sqliteResults = await SQL$RescriptBun.query(sqlite, [
  `
  SELECT * FROM users 
  WHERE active = `,
  `
`
], [1.0]);

export {
  mysql,
  mysqlResults,
  sqlite,
  sqliteResults,
}
/* mysql Not a pure module */
