// Generated by ReScript, PLEASE EDIT WITH CARE


let data = "hello world";

let encoded = btoa(data);

let decoded = atob(encoded);

console.log(encoded, decoded);

export {
  data,
  encoded,
  decoded,
}
/* encoded Not a pure module */
