// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "hello world";

var encoded = btoa(data);

var decoded = atob(encoded);

console.log(encoded, decoded);

export {
  data ,
  encoded ,
  decoded ,
}
/* encoded Not a pure module */
