// Generated by ReScript, PLEASE EDIT WITH CARE


function instanceOfClass(instance, _class) {
  try {
    return (instance instanceof _class);
  } catch {
    return false;
  }
}
;

function instanceOfClass$1(instance, class_) {
  return instanceOfClass(instance, class_);
}

export {
  instanceOfClass$1 as instanceOfClass,
}
/*  Not a pure module */
