// Generated by ReScript, PLEASE EDIT WITH CARE


var _NEGATIVE_ONE = BigInt(-1);

function mod(prim0, prim1) {
  return prim0 % prim1;
}

var $star$star = (function (a, b) { return (a ** b); });

function lnot(x) {
  return x ^ _NEGATIVE_ONE;
}

function modulo(prim0, prim1) {
  return prim0 % prim1;
}

function logicalNot(x) {
  return x ^ _NEGATIVE_ONE;
}

var power = $star$star;

export {
  mod ,
  $star$star ,
  lnot ,
  modulo ,
  power ,
  logicalNot ,
}
/* _NEGATIVE_ONE Not a pure module */
