// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(evt) {
  let match = typeof evt;
  if (match === "symbol") {
    return {
      TAG: "Symbol",
      _0: evt
    };
  } else if (match === "string") {
    return {
      TAG: "String",
      _0: evt
    };
  } else {
    return "Unknown";
  }
}

function eq(event1, event2) {
  let match = typeof event1;
  let match$1 = typeof event2;
  if (match === "symbol") {
    if (match$1 === "symbol") {
      return event1 === event2;
    } else {
      return false;
    }
  } else if (match === "string" && match$1 === "string") {
    return event1 === event2;
  } else {
    return false;
  }
}

export {
  classify,
  eq,
}
/* No side effect */
