// Generated by ReScript, PLEASE EDIT WITH CARE


var Dirent = {};

var Dir = {};

var Stats = {};

var Constants = {};

var Flag = {};

var FileHandle = {};

var PromiseAPI = {};

var Impl = {};

var WriteStream = {
  Impl: Impl
};

var Impl$1 = {};

var ReadStream = {
  Impl: Impl$1
};

export {
  Dirent ,
  Dir ,
  Stats ,
  Constants ,
  Flag ,
  FileHandle ,
  PromiseAPI ,
  WriteStream ,
  ReadStream ,
}
/* No side effect */
