// Generated by ReScript, PLEASE EDIT WITH CARE


let Dirent = {};

let Dir = {};

let Stats = {};

let Constants = {};

let Flag = {};

let FileHandle = {};

let PromiseAPI = {};

let Impl = {};

let WriteStream = {
  Impl: Impl
};

let Impl$1 = {};

let ReadStream = {
  Impl: Impl$1
};

export {
  Dirent,
  Dir,
  Stats,
  Constants,
  Flag,
  FileHandle,
  PromiseAPI,
  WriteStream,
  ReadStream,
}
/* No side effect */
