// Generated by ReScript, PLEASE EDIT WITH CARE


let BufferSource = {};

let HeadersInit = {};

let Headers = {};

let FormData = {};

let AbortSignal = {};

let ReadableStreamDirectController = {};

let WritableStreamDefaultWriter = {};

let WritableStream = {
  WritableStreamDefaultWriter: WritableStreamDefaultWriter
};

let ReadableStreamGenericReader = {};

let ReadableStreamDefaultReader = {};

let ReadableStream = {};

let ReadableWritablePair = {};

let Controller = {};

let TransformStream = {
  Controller: Controller
};

let Blob = {};

let File = {};

let URLSearchParams = {};

let Response = {};

let XMLHttpRequestBodyInit = {};

let BodyInit = {};

let Request = {};

let Crypto = {};

let TextEncoder = {};

let Input = {};

let TextDecoder = {
  Input: Input
};

let EventTarget = {};

let Event = {};

let ErrorEvent = {};

let CloseEvent = {};

let MessageEvent = {};

let CustomEvent = {};

let WebSocket = {};

let URL = {};

let FetchEvent = {};

let ShellOutput = {};

let ShellExpression = {};

let ShellPromise = {};

let Shell = {};

export {
  BufferSource,
  HeadersInit,
  Headers,
  FormData,
  AbortSignal,
  ReadableStreamDirectController,
  WritableStream,
  ReadableStreamGenericReader,
  ReadableStreamDefaultReader,
  ReadableStream,
  ReadableWritablePair,
  TransformStream,
  Blob,
  File,
  URLSearchParams,
  Response,
  XMLHttpRequestBodyInit,
  BodyInit,
  Request,
  Crypto,
  TextEncoder,
  TextDecoder,
  EventTarget,
  Event,
  ErrorEvent,
  CloseEvent,
  MessageEvent,
  CustomEvent,
  WebSocket,
  URL,
  FetchEvent,
  ShellOutput,
  ShellExpression,
  ShellPromise,
  Shell,
}
/* No side effect */
