// Generated by ReScript, PLEASE EDIT WITH CARE


var BufferSource = {};

var HeadersInit = {};

var $$Headers = {};

var $$FormData = {};

var $$AbortSignal = {};

var ReadableStreamDirectController = {};

var $$WritableStreamDefaultWriter = {};

var $$WritableStream = {
  $$WritableStreamDefaultWriter: $$WritableStreamDefaultWriter
};

var ReadableStreamGenericReader = {};

var $$ReadableStreamDefaultReader = {};

var $$ReadableStream = {};

var ReadableWritablePair = {};

var Controller = {};

var $$TransformStream = {
  Controller: Controller
};

var $$Blob = {};

var $$File = {};

var $$URLSearchParams = {};

var $$Response = {};

var XMLHttpRequestBodyInit = {};

var BodyInit = {};

var $$Request = {};

var $$Crypto = {};

var $$TextEncoder = {};

var Input = {};

var $$TextDecoder = {
  Input: Input
};

var $$EventTarget = {};

var $$Event = {};

var $$ErrorEvent = {};

var $$CloseEvent = {};

var $$MessageEvent = {};

var $$CustomEvent = {};

var $$WebSocket = {};

var $$URL = {};

var FetchEvent = {};

var ShellOutput = {};

var ShellExpression = {};

var ShellPromise = {};

var Shell = {};

export {
  BufferSource ,
  HeadersInit ,
  $$Headers ,
  $$FormData ,
  $$AbortSignal ,
  ReadableStreamDirectController ,
  $$WritableStream ,
  ReadableStreamGenericReader ,
  $$ReadableStreamDefaultReader ,
  $$ReadableStream ,
  ReadableWritablePair ,
  $$TransformStream ,
  $$Blob ,
  $$File ,
  $$URLSearchParams ,
  $$Response ,
  XMLHttpRequestBodyInit ,
  BodyInit ,
  $$Request ,
  $$Crypto ,
  $$TextEncoder ,
  $$TextDecoder ,
  $$EventTarget ,
  $$Event ,
  $$ErrorEvent ,
  $$CloseEvent ,
  $$MessageEvent ,
  $$CustomEvent ,
  $$WebSocket ,
  $$URL ,
  FetchEvent ,
  ShellOutput ,
  ShellExpression ,
  ShellPromise ,
  Shell ,
}
/* No side effect */
