// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Net$RescriptBun from "./Net.js";

let Events = {};

let Impl = {};

let IncomingMessage = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let ClientRequest = {
  Events: Events$1,
  Impl: Impl$1
};

let Events$2 = {};

let Impl$2 = {};

let ServerResponse = {
  Events: Events$2,
  Impl: Impl$2
};

let Agent = {};

let Events$3 = {};

let Impl$3 = {};

let Server = {
  Events: Events$3,
  Impl: Impl$3
};

export {
  IncomingMessage,
  ClientRequest,
  ServerResponse,
  Agent,
  Server,
}
/* Net-RescriptBun Not a pure module */
