// Generated by ReScript, PLEASE EDIT WITH CARE


let Events = {};

let Impl = {};

let Http2Stream = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let ClientHttp2Stream = {
  Events: Events$1,
  Impl: Impl$1
};

let Events$2 = {};

let Impl$2 = {};

let ServerHttp2Stream = {
  Events: Events$2,
  Impl: Impl$2
};

let Http2Session = {};

let Origin = {};

let ServerHttp2Session = {
  Origin: Origin
};

let Impl$3 = {};

let Http2ServerRequest = {
  Impl: Impl$3
};

let Impl$4 = {};

let Http2ServerResponse = {
  Impl: Impl$4
};

export {
  Http2Stream,
  ClientHttp2Stream,
  ServerHttp2Stream,
  Http2Session,
  ServerHttp2Session,
  Http2ServerRequest,
  Http2ServerResponse,
}
/* No side effect */
