// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tls$RescriptBun from "./Tls.js";

let Events = {};

let Impl = {};

let HttpsServer = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Agent = {
  Events: Events$1
};

export {
  HttpsServer,
  Agent,
}
/* Tls-RescriptBun Not a pure module */
