// Generated by ReScript, PLEASE EDIT WITH CARE


var Events = {};

var Impl = {};

var Http2Stream = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var ClientHttp2Stream = {
  Events: Events$1,
  Impl: Impl$1
};

var Events$2 = {};

var Impl$2 = {};

var ServerHttp2Stream = {
  Events: Events$2,
  Impl: Impl$2
};

var Http2Session = {};

var Origin = {};

var ServerHttp2Session = {
  Origin: Origin
};

var Impl$3 = {};

var Http2ServerRequest = {
  Impl: Impl$3
};

var Impl$4 = {};

var Http2ServerResponse = {
  Impl: Impl$4
};

export {
  Http2Stream ,
  ClientHttp2Stream ,
  ServerHttp2Stream ,
  Http2Session ,
  ServerHttp2Session ,
  Http2ServerRequest ,
  Http2ServerResponse ,
}
/* No side effect */
