// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Net$RescriptBun from "./Net.js";

var Events = {};

var Impl = {};

var IncomingMessage = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var ClientRequest = {
  Events: Events$1,
  Impl: Impl$1
};

var Events$2 = {};

var Impl$2 = {};

var ServerResponse = {
  Events: Events$2,
  Impl: Impl$2
};

var Agent = {};

var Events$3 = {};

var Impl$3 = {};

var Server = {
  Events: Events$3,
  Impl: Impl$3
};

export {
  IncomingMessage ,
  ClientRequest ,
  ServerResponse ,
  Agent ,
  Server ,
}
/* Net-RescriptBun Not a pure module */
