// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tls$RescriptBun from "./Tls.js";

var Events = {};

var Impl = {};

var HttpsServer = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Agent = {
  Events: Events$1
};

export {
  HttpsServer ,
  Agent ,
}
/* Tls-RescriptBun Not a pure module */
