// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$RescriptBun from "./EventEmitter.js";

var Events = {};

var Impl = {};

EventEmitter$RescriptBun.Impl({});

var Socket = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var TcpSocket = {
  Events: Events$1,
  Impl: Impl$1
};

var Events$2 = {};

var Impl$2 = {};

var IcpSocket = {
  Events: Events$2,
  Impl: Impl$2
};

var Events$3 = {};

var Impl$3 = {};

var Server = {
  Events: Events$3,
  Impl: Impl$3
};

var Events$4 = {};

var Impl$4 = {};

var TcpServer = {
  Events: Events$4,
  Impl: Impl$4
};

var Events$5 = {};

var Impl$5 = {};

var IcpServer = {
  Events: Events$5,
  Impl: Impl$5
};

export {
  Socket ,
  TcpSocket ,
  IcpSocket ,
  Server ,
  TcpServer ,
  IcpServer ,
}
/*  Not a pure module */
