// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$RescriptBun from "./EventEmitter.js";

let Events = {};

let Impl = {};

EventEmitter$RescriptBun.Impl({});

let Socket = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let TcpSocket = {
  Events: Events$1,
  Impl: Impl$1
};

let Events$2 = {};

let Impl$2 = {};

let IcpSocket = {
  Events: Events$2,
  Impl: Impl$2
};

let Events$3 = {};

let Impl$3 = {};

let Server = {
  Events: Events$3,
  Impl: Impl$3
};

let Events$4 = {};

let Impl$4 = {};

let TcpServer = {
  Events: Events$4,
  Impl: Impl$4
};

let Events$5 = {};

let Impl$5 = {};

let IcpServer = {
  Events: Events$5,
  Impl: Impl$5
};

export {
  Socket,
  TcpSocket,
  IcpSocket,
  Server,
  TcpServer,
  IcpServer,
}
/*  Not a pure module */
