// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeperf_hooks from "node:perf_hooks";
import * as Js_null_undefined from "rescript/lib/es6/Js_null_undefined.js";

let PerformanceEntry = {};

let PerformanceNodeTiming = {};

let Performance = {};

let Histogram = {};

function getEntriesByName(entryList, type_, name) {
  return entryList.getEntriesByName(name, Js_null_undefined.fromOption(type_));
}

let PerformanceObserverEntryList = {
  getEntriesByName: getEntriesByName
};

let PerformanceObserver = {};

function monitorEventLoopDelay(resolution, param) {
  return Nodeperf_hooks.eventLoopDelay(Js_null_undefined.fromOption(resolution));
}

export {
  PerformanceEntry,
  PerformanceNodeTiming,
  Performance,
  Histogram,
  PerformanceObserverEntryList,
  PerformanceObserver,
  monitorEventLoopDelay,
}
/* node:perf_hooks Not a pure module */
