// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeperf_hooks from "node:perf_hooks";
import * as Js_null_undefined from "rescript/lib/es6/js_null_undefined.js";

var $$PerformanceEntry = {};

var PerformanceNodeTiming = {};

var $$Performance = {};

var Histogram = {};

function getEntriesByName(entryList, type_, name) {
  return entryList.getEntriesByName(name, Js_null_undefined.fromOption(type_));
}

var $$PerformanceObserverEntryList = {
  getEntriesByName: getEntriesByName
};

var $$PerformanceObserver = {};

function monitorEventLoopDelay(resolution, param) {
  return Nodeperf_hooks.eventLoopDelay(Js_null_undefined.fromOption(resolution));
}

export {
  $$PerformanceEntry ,
  PerformanceNodeTiming ,
  $$Performance ,
  Histogram ,
  $$PerformanceObserverEntryList ,
  $$PerformanceObserver ,
  monitorEventLoopDelay ,
}
/* node:perf_hooks Not a pure module */
