// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";
import * as Nodeperf_hooks from "node:perf_hooks";

let PerformanceEntry = {};

let PerformanceNodeTiming = {};

let Performance = {};

let Histogram = {};

function getEntriesByName(entryList, type_, name) {
  return entryList.getEntriesByName(name, Stdlib_Nullable.fromOption(type_));
}

let PerformanceObserverEntryList = {
  getEntriesByName: getEntriesByName
};

let PerformanceObserver = {};

function monitorEventLoopDelay(resolution, param) {
  return Nodeperf_hooks.eventLoopDelay(Stdlib_Nullable.fromOption(resolution));
}

export {
  PerformanceEntry,
  PerformanceNodeTiming,
  Performance,
  Histogram,
  PerformanceObserverEntryList,
  PerformanceObserver,
  monitorEventLoopDelay,
}
/* node:perf_hooks Not a pure module */
