// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$RescriptBun from "./EventEmitter.js";

EventEmitter$RescriptBun.Impl({});

let Interface = {};

function close(rl, f) {
  return rl.on("close", f);
}

function line(rl, f) {
  return rl.on("line", f);
}

function history(rl, f) {
  return rl.on("history", f);
}

let Events = {
  close: close,
  line: line,
  history: history
};

export {
  Interface,
  Events,
}
/*  Not a pure module */
