// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";

var RedisClient = {};

var redis = new $$Bun.RedisClient();

export {
  RedisClient ,
  redis ,
}
/* redis Not a pure module */
