// Generated by ReScript, PLEASE EDIT WITH CARE


let SQLQuery = {};

let fromArray = (function(array) {
      array.raw = [...array]
      return array
    });

let TemplateStringsArray = {
  fromArray: fromArray
};

let query = (function(t, strings, params) {
    let templateArray = TemplateStringsArray.fromArray(strings)

    return t(templateArray, ...params)
  });

let object = (function(t, obj, cols) {
    return t(obj, ...cols)
  });

let values = (function(t, values) {
    return t(arr)
  });

export {
  SQLQuery,
  TemplateStringsArray,
  query,
  object,
  values,
}
/* No side effect */
