// Generated by ReScript, PLEASE EDIT WITH CARE


var SQLQuery = {};

var fromArray = (function(array) {
      array.raw = [...array]
      return array
    });

var TemplateStringsArray = {
  fromArray: fromArray
};

var query = (function(t, strings, params) {
    let templateArray = TemplateStringsArray.fromArray(strings)

    return t(templateArray, ...params)
  });

var object = (function(t, obj, cols) {
    return t(obj, ...cols)
  });

var values = (function(t, values) {
    return t(arr)
  });

export {
  SQLQuery ,
  TemplateStringsArray ,
  query ,
  object ,
  values ,
}
/* No side effect */
