// Generated by ReScript, PLEASE EDIT WITH CARE


let Events = {};

let Impl = {};

let Common = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let Writable = {
  Events: Events$1,
  Impl: Impl$1
};

let Events$2 = {};

let Impl$2 = {};

let Readable = {
  Events: Events$2,
  Impl: Impl$2
};

let Events$3 = {};

let Impl$3 = {};

let Duplex = {
  Events: Events$3,
  Impl: Impl$3
};

let Events$4 = {};

let Impl$4 = {};

let Transform = {
  Events: Events$4,
  Impl: Impl$4
};

let Events$5 = {};

let Impl$5 = {};

let PassThrough = {
  Events: Events$5,
  Impl: Impl$5
};

let Events$6 = {};

export {
  Common,
  Writable,
  Readable,
  Duplex,
  Transform,
  PassThrough,
  Events$6 as Events,
}
/* No side effect */
