// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Net$RescriptBun from "./Net.js";

let Events = {};

let Impl = {};

let TlsSocket = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let TlsServer = {
  Events: Events$1,
  Impl: Impl$1
};

export {
  TlsSocket,
  TlsServer,
}
/* Net-RescriptBun Not a pure module */
