// Generated by ReScript, PLEASE EDIT WITH CARE


let Events = {};

let Impl = {};

let ReadStream = {
  Events: Events,
  Impl: Impl
};

let Events$1 = {};

let Impl$1 = {};

let WriteStream = {
  Events: Events$1,
  Impl: Impl$1
};

export {
  ReadStream,
  WriteStream,
}
/* No side effect */
