// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeurl from "node:url";
import * as Js_null_undefined from "rescript/lib/es6/Js_null_undefined.js";

let SearchParams = {};

function format(auth, fragment, search, unicode, url) {
  return Nodeurl.format(url, {
    auth: Js_null_undefined.fromOption(auth),
    fragment: Js_null_undefined.fromOption(fragment),
    search: Js_null_undefined.fromOption(search),
    unicode: Js_null_undefined.fromOption(unicode)
  });
}

export {
  SearchParams,
  format,
}
/* node:url Not a pure module */
