// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeurl from "node:url";
import * as Stdlib_Nullable from "@rescript/runtime/lib/es6/Stdlib_Nullable.js";

let SearchParams = {};

function format(auth, fragment, search, unicode, url) {
  return Nodeurl.format(url, {
    auth: Stdlib_Nullable.fromOption(auth),
    fragment: Stdlib_Nullable.fromOption(fragment),
    search: Stdlib_Nullable.fromOption(search),
    unicode: Stdlib_Nullable.fromOption(unicode)
  });
}

export {
  SearchParams,
  format,
}
/* node:url Not a pure module */
