// Generated by ReScript, PLEASE EDIT WITH CARE


function WithMessageType(T) {
  return {};
}

let MessagePort = {
  WithMessageType: WithMessageType
};

function WithMessageTypes(T) {
  return {};
}

let MessageChannel = {
  WithMessageTypes: WithMessageTypes
};

function WithMessageType$1(T) {
  return {};
}

let Worker = {
  WithMessageType: WithMessageType$1
};

function WithMessageType$2(T) {
  let Worker = {};
  return {
    Worker: Worker
  };
}

export {
  MessagePort,
  MessageChannel,
  Worker,
  WithMessageType$2 as WithMessageType,
}
/* No side effect */
