// Generated by ReScript, PLEASE EDIT WITH CARE


function WithMessageType(T) {
  return {};
}

var $$MessagePort = {
  WithMessageType: WithMessageType
};

function WithMessageTypes(T) {
  return {};
}

var $$MessageChannel = {
  WithMessageTypes: WithMessageTypes
};

function WithMessageType$1(T) {
  return {};
}

var $$Worker = {
  WithMessageType: WithMessageType$1
};

function WithMessageType$2(T) {
  var $$Worker = {};
  return {
          $$Worker: $$Worker
        };
}

export {
  $$MessagePort ,
  $$MessageChannel ,
  $$Worker ,
  WithMessageType$2 as WithMessageType,
}
/* No side effect */
