// Generated by ReScript, PLEASE EDIT WITH CARE


var TransferListItem = {};

var $$MessagePort = {};

var WorkerEnv = {};

var $$Worker = {};

var $$BroadcastChannel = {};

var $$MessageChannel = {};

export {
  TransferListItem ,
  $$MessagePort ,
  WorkerEnv ,
  $$Worker ,
  $$BroadcastChannel ,
  $$MessageChannel ,
}
/* No side effect */
