// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";

Buntest.describe("Playing around with tests", () => {
  Buntest.test("addition works", () => {
    Buntest.expect(2).toBe(2);
  });
});

/*  Not a pure module */
